version: "3.7"

services:

  servidorweb:
    build: ./intracorp
    ports:
      - "3000:3000"
    networks:
      redinterna:
    depends_on:
      - db

  db:
    image: mongo:4
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      redinterna:
        aliases:
          - mongo

  cookie-listener:
    build: ./cookie-listener
    ports:
      - "4000:4000"
    networks:
      redexterna:
    
networks:
  redinterna:
  redexterna: